import matplotlib.pyplot as plt
import pandas as pd


def set_pandas_display_options(df):
    """ Sets the pandas display options based on the shape of the dataframe

    :param DataFrame df: the data
    """
    pd.set_option('display.max_rows', df.shape[0] + 1)
    pd.set_option('display.max_columns', df.shape[1] + 1)


if __name__ == '__main__':
    #df = pd.read_csv('Data/Prepared_dataset.csv', parse_dates=['utc'], dtype={'utc': str})
    #set_pandas_display_options(df)

    # 1. Print the stats generated by describe
    #print(df.describe())

    # 2. Generate a box plot to show the outliers (in a same box with same scale)
    #bp = df.plot.box()
    #plt.show()

    # 3. Generate box plots to show the outliers (in separate boxes with different scale)
    #bp_sub = df.plot.box(subplots=True)
    #plt.show()

    # 4. Generate a line plot of the data
    #cols = ["PM2.5", "PM10", "Total"]
    #df = pd.read_csv('data/Prepared_dataset.csv', usecols=cols)
    #line_plot = df.plot.line()
    #plt.show()

    # 5. Create two new dataframes, one with PM2.5 data and one with PM10 data
    #df_PM25 = df.loc[df['PM2.5'] == 'PM2.5']
    #df_PM10 = df.loc[df['PM10'] == 'PM10']

    # 6. Reset the index of each of the new dataframes
    #df_PM25.reset_index(drop=True, inplace=True)
    #df_PM10.reset_index(drop=True, inplace=True)

    # 7. Create two line plots, for each x will be 'Year' and y will be the variable 'cols'
    #df = pd.read_csv('data/Prepared_dataset.csv', parse_dates=['utc'], dtype={'utc': str, 'unit':str})
    #cols = ["PM2.5", "PM10", "Total"]

    #df_PM25 = df.loc[df['PM2.5'] == 'PM2.5']
    #df_PM10 = df.loc[df['PM10'] == 'PM10']

    df_PM25.reset_index(drop=True, inplace=True)
    df_PM10.reset_index(drop=True, inplace=True)

    lp_PM25 = df_PM25.plot.line(x='utc', y=cols, title='PM2.5', xticks=df_PM25.index)
    lp_PM25.set_xticklabels(df_PM25['utc'])
    plt.xticks(rotation=90)
    plt.show()
